---
title: "stp25tools"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings=FALSE)
require(stp25tools)
require(effects)
# require(stpvers)
# 
# set_my_options(prozent = list(
#   digits = c(0, 0),
#   style = 2,
#   null_percent_sign = "."
# ))
# scale2<- function(x, mn=1, mx=5){
# x<-  x-min(x, na.rm=TRUE)
# x<-  x/max(x, na.rm=TRUE)
# x*(mx -1 ) + mn
# }
# set.seed(1234)
# 
# require(lavaan)
```



<!-- Attaching package: ‘stp25tools’ -->

<!-- The following objects are masked from ‘package:stp25aggregate’: -->

<!--     get_label, Label, set_label, wrap_label, XLS -->


## add_to


Element zu Liste hinzufügen.

```{r add_to-list}
add_to(list(a = 1:3, b = LETTERS[1:5]),
       c = 1, d = 2)


```


Element zu Data-Frame hinzufügen.

```{r}
df <-   data.frame(
Source = c("A", "B", "C", "F"),
x = 1:4,
y = 1:4,
stringsAsFactors = FALSE
)

 add_to(df, c("Erste Zeile" = 1, "Dritte" = 3))

add_to(df, "Erste Zeile")
add_to(df, c("Erste Zeile", "Zweite"))
add_to(df, c("Erste Zeile" = 1, "letzte" = 5))
```

```{r}
add_to(df, list("G", 5), pos = -1)
add_to(df, data.frame(  Source = c("G", "H"),
                        x = 5:6
), pos = -1)
```



## cbind() und rbind()

```{r}
df1 = data.frame(CustomerId = c(1:6), Product = c(rep("Oven", 3), rep("Television", 3)))
df2 = data.frame(CustomerId = c(4:7), Product = c(rep("Television", 2), rep("Air conditioner", 2)))
df3 = data.frame(
   CustomerId = c(4:7),
   Product = c(rep("Television", 2), rep("Air conditioner", 2)),
   State = c(rep("California", 2), rep("New Jersey", 2))
 )

 Rbind2(df1, df3)
 #dplyr::bind_rows(df1, df2)
```


## merge()

```{r}
n<-10
df1 <- 
  data.frame(
  origin = sample(c("A", "B", "C", "D", "E"), n, replace = T),
  N = sample(seq(9, 27, 0.5), n, replace = T),
  P = sample(seq(0.3, 4, 0.1), n, replace = T),
  C = sample(seq(400, 500, 1), n, replace = T))
df2 <-
  data.frame(
    origin = sample(c("A", "B", "C", "D", "E"), n, replace = T),
    foo1 = sample(c(T, F), n, replace = T),
    X = sample(seq(145600, 148300, 100), n, replace = T),
    Y = sample(seq(349800, 398600, 100), n, replace = T))
df3 <-
  data.frame(origin = sample(c("A", "B", "C", "D", "E"), n, replace = T))
df4 <-
  data.frame(origin = sample(c("A", "B", "C", "D", "E"), n, replace = T))

df1$id <- df2$id <- df3$id <- df4$id <- paste("P", sprintf("%02d", c(1:n)), sep = "")  
 
Merge2(df1, df2, df3, df4, by = "id")
 
```
 
 
 
##  cbind data.frame aber listenweise

```{r}
m <- data.frame(
  Item = 1:3,
  a = (1:3),
  b = (1:3) * 2,
  c = (1:3) * 3
)
sd <- data.frame(
  Item = (1:3),
  a = (1:3) * 4,
  b = (1:3) * 5,
  c = (1:3) * 6
)
combine_data_frame(m, sd)
combine_data_frame(m, sd, by = NULL)
```



## list_to_df



```{r}
x <- list(
  M1 = data.frame(
    Source = c("Intercept", "A", "B" , "C", "Residual"),
    b = c(0, 1, 2, 3, 0),
    y = c((1:4) + 10, 0)
  ),

  M2 = data.frame(
    Source = c("Intercept", "A", "C", "B",  "D",  "E", "Residual"),
    x = c(0, 1, 3, 2, 4, 5, 0),
    y = c((1:6) + 21, 0)
  ),
  M3 = data.frame(
    Source = c("A", "B", "C", "D", "Residual"),
    x = c((1:4), 0),
    y = c((1:4) + 20, 0)
  ),

  M1 = data.frame(
    Source = c("A", "B",  "D", "Residual"),
    x = c(1, 2, 4, 0),
    y = c((1:3) + 30, 0)
  )

)

# Spezialfall
list_to_df(x, last = "Residual")


fix_to_df(x)


```

```{r}

data(infert, package = "datasets")
infert$case  <- factor(infert$case ,1:0, c("case", "control") )

#infert$spontaneous <- factor(infert$spontaneous)
#infert$induced2    <- factor(infert$induced==0)
# tab_1<- xtabs(~  case, infert)
# tab_2x2<- xtabs(~ induced2 + case, infert)
tab_3x2<- xtabs(~ induced + case, infert)
# tab_3x3<- xtabs(~ induced + education, infert)
# tab_3x3x2<- xtabs(~ induced + education+case, infert)
# tab_3x2x3<- xtabs(~ induced +case+ education, infert)
 
tab_3x2
fix_to_df(tab_3x2)


```

# auto_trans

Automatische Taranformation von numerischen Variablen entsprechend ihere Verteilungseigenschaft

 
```{r}
 
x <- c(1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 9, 20, 30)
x_trans<-auto_trans(x)
auto_trans(x_trans)
x <- 100 - x
auto_trans(x)
```



```{r sim-data, include=FALSE}

n <- 100
set.seed(n)
x1 = rnorm(100)+5
x2 = rlnorm(n, meanlog = 0, sdlog = 1)+1
x3 = rpois(n, lambda = 1)+1
x4 = rweibull(n, shape = .8, scale = 1)+10
x5 = runif(n, min = 0, max = 100)+1
x.neg <- rbeta(n, 5, 2)  # Negative Skew
x.pos <- rexp(n, 1) # Positive Skew
dat<-
  data.frame(
    morm= x1[order(x1)],
    beta=x.neg[order(x.neg)],
    exp = x.pos[order(x.pos)],
   # lnorm= x2[order(x2)],
    pois= x3[order(x3)],
   # weibull= x4[order(x4)],
  #  unif= x5[order(x5)],
    group= factor(c(rep(1, n*.5), rep(1:2, n*0.3/2), rep(2, n*0.2)))
  )
```


 
```{r boxplots, fig.height=6, fig.width=6}
par(mfrow=c(2,2))

boxplot(beta~group, dat)
boxplot(auto_trans(beta, treshhold = .4)~group, dat)
boxplot(exp~group, dat)
boxplot(auto_trans(exp, treshhold = .4)~group, dat)
#boxplot(weibull~group, dat)
#boxplot(unif~group, dat)

```

```{r model-fit, fig.height=2.5, fig.width=7}
for(i in 1:4){

  dat$x<- dat[[i]]
  fit0 <- lm(x~ group, dat)
  dat$x<- auto_trans(dat$x, treshhold = .4)
  fit1 <- lm(x~ group, dat)



  p0<-plot(effect("group", fit0),
           main="orginal",
           ylab = names(dat)[i])
  p1<-plot(effect("group", fit1),
           main="non-trans",
           ylab = "")
  p2<-plot(effect("group", fit1,
                  transformation =
                    list(link = attr(dat$x, "link"),
                         inverse = attr(dat$x, "inverse"))),
           main=attr(dat$x, "name"),
           ylab = ""
           )
   gridExtra::grid.arrange(p0, p1, p2, ncol = 3)
}

```







